### ISSUE TITLE
如果流程文件冲突了怎么办

### ISSUE THREAD

**Issue by ykdsg** [hejiehui/xUnit#1]
图形可视化非常赞，但是如果xunit文件冲突了怎么办？是否还是需要通过xml来解决冲突

**Comment by hejiehui** [comment]
什么叫文件冲突？同名吗？请详细说明一下

**Comment by ykdsg** [comment]
比如在一个项目组中，A调整了xunit的文件先提交到gitlab上，B也调整这个文件，提交的时候提示冲突了

**Comment by hejiehui** [comment]
xunit的xml格式是层次递进的，如果修改的是不同的组件，一般可以自动合并。如果是相同的，比如同时添加了两个true的bibranch单元，则只有手工操作，你需要和修改的另一方沟通一下，以谁为准
