### ISSUE TITLE
IDEA 2022.2使用该插件卡死

### ISSUE THREAD

**Issue by Daryl494** [hejiehui/xUnit#13]
你好，我用的是IDEA 2022.2版本，安装了IDEA的插件（插件版本2.0.2）后打开xunit文件，能够打开这个文件的页面，但此后IDEA就会卡死无法退出，并报错HIDE_DEFAULT_EDITOR is supported only for DumbAware providers, class com.xrosstools.xunit.idea.editor.XrossUnitEditorProvider is not DumbAware，可以问下这是什么原因导致的吗？

**Comment by hejiehui** [comment]
新版本已经解决这个问题，并且已经发布到IDEA的marketplace，可以直接从IDEA plugins升级
https://plugins.jetbrains.com/plugin/21413-xross-unit-editor
